"use client";


import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/NavBar";
import DropDownMenu from "@/component/DropDownMenu";
import { useState } from "react";
import Footer from "@/component/Footer";




const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [displayMenu, setDisplayMenu] = useState(false);

  return (
    <html lang="en">
      <body className={`w-[100%] overflow-x-hidden ${displayMenu === true ? 'overflow-y-hidden' : ''} min-h-screen relative ${poppins.className}`}>
        <NavBar setDisplayMenu={setDisplayMenu} />
        <DropDownMenu displayMenu={displayMenu} setDisplayMenu={setDisplayMenu} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
